---
- hosts: monitoringservers
  become: yes
  vars_prompt:
  - name: "root_password"
    prompt: "What is your SQL root password: "

  tasks:
  - name: Import .sql file into MySQL
    mysql_db:
      login_user: "root"
      login_password: "{{ root_password }}"
      name: all
      state: import
      target: /home/local_admin/Git/Monitoring/MySQL/Monitoring.sql
